---
  - name: Generate IOS Router Configurations
    connection: network_cli
    hosts: us33
    gather_facts: no

    tasks:
       
      - name: Deploy Configuration
        ios_config:
          src: configs/{{ inventory_hostname }}

      

