---
 - name: Deploy Cisco IOS-XE Router Configurations
   connection: local
   hosts: us33
   gather-facts: no
   vars:
     creds:
       hostname: "us33-core-switch"
       username: "admin"
       password: "password123"
       dev_os: "ios"
   tasks:
     - napalm_install_config:
         provider: "{{ creds }}"
         config_file: "configs/{{ inventory_hostname }}"
         commit_changes: False
