---
  - name: Generate IOS Router Configurations
    connection: network_cli
    hosts: us33-core-switch
    gather_facts: no

    tasks:
       
      - name: Deploy Configuration
        ios_config:
          src: config/us33-core-switch
          
      

