---
  - name: Generate IOS Router Configurations
    connection: local
    hosts: SCSVARS
    gather_facts: no
    tasks:
      - template:
          src=templates/var-template.j2
          dest=configs/{{ inventory_hostname }}
