---
  - name: Generate IOS Router Configurations
    connection: local
    hosts: SCS
    gather_facts: no
    tasks:
      - template:
          src=templates/scs-template.j2
          dest=configs/{{ inventory_hostname }}
