---
  - name: IOS Config
    hosts: us33-core-switch
    connection: network_cli
    gather_facts: no

    tasks:
      - name: Configure SNP
        ios_config:
          commands:
            - snmp-server community ansible-public RO
            - snmp-server community ansible-private RW
            - snmp-server community ansible-test RO
                        
  - name: Hardening from file
    hosts: us33-core-switch
    connection: network_cli
    gather_facts: no
    
    tasks:
      - name: Ensure that routers are secure
        ios_config:
          src: hardening.cfg